# Generated by Django 2.2.10 on 2020-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', verbose_name=models.CharField(default='', max_length=255, null=True)),
            preserve_default=False,
        ),
    ]
